const { describe, it } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');

const {
  compareScripts,
  getOutdatedScripts,
  hasScaffoldedScripts,
  readScriptVersion,
} = require('../dist/core/scaffoldScripts');

function mkTemp(prefix) {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

describe('scaffoldScripts', () => {
  it('readScriptVersion parses the generated header', () => {
    const file = path.join(mkTemp('leb-scr-ver-'), 'build.js');
    fs.writeFileSync(file, '// Generated by local-expo-build v0.4.2\n');
    assert.equal(readScriptVersion(file), '0.4.2');
  });

  it('getOutdatedScripts returns files that differ from bundled templates', () => {
    const cwd = mkTemp('leb-scr-out-');
    const scriptsDir = path.join(cwd, 'scripts');
    fs.mkdirSync(scriptsDir, { recursive: true });

    const tplBuild = path.join(__dirname, '..', 'templates', 'scripts', 'build.js');
    fs.copyFileSync(tplBuild, path.join(scriptsDir, 'build.js'));

    const stale = path.join(scriptsDir, 'pin-gradle.js');
    fs.writeFileSync(stale, '// Generated by local-expo-build v0.1.0\n// old\n');

    assert.equal(hasScaffoldedScripts(cwd), true);
    const outdated = getOutdatedScripts(cwd);
    assert.ok(outdated.some((s) => s.name === 'pin-gradle.js'));
    assert.ok(!outdated.some((s) => s.name === 'build.js'));
  });

  it('compareScripts marks missing files as not existing', () => {
    const cwd = mkTemp('leb-scr-miss-');
    const statuses = compareScripts(cwd);
    assert.equal(statuses.length > 0, true);
    assert.equal(statuses.every((s) => !s.exists), true);
  });
});
