const { describe, it } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');

const {
  applyScriptUpdates,
  compareScripts,
  getOutdatedScripts,
  hasScaffoldedScripts,
  readScriptVersion,
  scaffoldProject,
} = require('../dist/core/scaffoldScripts');

function mkTemp(prefix) {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

describe('scaffoldScripts', () => {
  it('readScriptVersion parses the generated header', () => {
    const file = path.join(mkTemp('leb-scr-ver-'), 'build.js');
    fs.writeFileSync(file, '// Generated by local-expo-build v0.4.2\n');
    assert.equal(readScriptVersion(file), '0.4.2');
  });

  it('getOutdatedScripts returns files that differ from bundled templates', () => {
    const cwd = mkTemp('leb-scr-out-');
    const scriptsDir = path.join(cwd, 'scripts');
    fs.mkdirSync(scriptsDir, { recursive: true });

    const tplBuild = path.join(__dirname, '..', 'templates', 'scripts', 'build.js');
    fs.copyFileSync(tplBuild, path.join(scriptsDir, 'build.js'));

    const stale = path.join(scriptsDir, 'pin-gradle.js');
    fs.writeFileSync(stale, '// Generated by local-expo-build v0.1.0\n// old\n');

    assert.equal(hasScaffoldedScripts(cwd), true);
    const outdated = getOutdatedScripts(cwd);
    assert.ok(outdated.some((s) => s.name === 'pin-gradle.js'));
    assert.ok(!outdated.some((s) => s.name === 'build.js'));
  });

  it('compareScripts marks missing files as not existing', () => {
    const cwd = mkTemp('leb-scr-miss-');
    const statuses = compareScripts(cwd);
    assert.equal(statuses.length > 0, true);
    assert.equal(statuses.every((s) => !s.exists), true);
  });

  it('scaffoldProject copies scripts and adds package.json npm scripts', () => {
    const cwd = mkTemp('leb-scr-proj-');
    fs.writeFileSync(
      path.join(cwd, 'package.json'),
      JSON.stringify({ name: 'x', version: '1.0.0' }, null, 2)
    );
    const result = scaffoldProject(cwd);

    // Scripts copied
    assert.ok(fs.existsSync(path.join(cwd, 'scripts', 'build.js')), 'build.js should exist');
    assert.ok(fs.existsSync(path.join(cwd, 'keystore.properties.example')), 'example should exist');
    assert.ok(result.wroteFiles.includes('build.js'));
    assert.ok(result.packageScriptsModified);

    // npm scripts added
    const pkg = JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'), 'utf8'));
    assert.equal(pkg.scripts['build:android:aab'], 'node scripts/build.js aab');
    assert.equal(pkg.scripts['build:android:apk'], 'node scripts/build.js apk');

    // Second (non-force) call is idempotent for existing identical files
    const second = scaffoldProject(cwd);
    assert.ok(second.skippedFiles.includes('build.js'));
    assert.equal(second.packageScriptsModified, false);
  });

  it('applyScriptUpdates copies template over user scripts', () => {
    const cwd = mkTemp('leb-scr-app-');
    const scriptsDir = path.join(cwd, 'scripts');
    fs.mkdirSync(scriptsDir, { recursive: true });
    fs.writeFileSync(path.join(scriptsDir, 'build.js'), '// stale\n');
    const statuses = compareScripts(cwd);
    const build = statuses.find((s) => s.name === 'build.js');
    assert.ok(build.contentDiffers, 'stale file should differ from template');
    applyScriptUpdates([build]);
    assert.equal(readScriptVersion(path.join(scriptsDir, 'build.js')) !== null, true);
  });

  it('scaffoldProject gitignores keystore secrets including *.p12 (A1)', () => {
    const cwd = mkTemp('leb-scr-gi-');
    fs.writeFileSync(
      path.join(cwd, 'package.json'),
      JSON.stringify({ name: 'x', version: '1.0.0' }, null, 2)
    );
    scaffoldProject(cwd);
    const gi = fs.readFileSync(path.join(cwd, '.gitignore'), 'utf8');
    for (const entry of ['keystore.properties', '*.jks', '*.p12', 'credentials.json']) {
      assert.ok(gi.includes(entry), `.gitignore should contain "${entry}"`);
    }
  });
});

describe('scaffolded template invariants (B7/B8)', () => {
  it('template build.js passes --non-interactive to expo prebuild (B8)', () => {
    const tpl = fs.readFileSync(
      path.join(__dirname, '..', 'templates', 'scripts', 'build.js'),
      'utf8'
    );
    assert.ok(tpl.includes("--non-interactive"), 'prebuild should run non-interactively');
  });

  it('template sync-eas-version.js checks projectId before reading build.gradle (B7)', () => {
    const tpl = fs.readFileSync(
      path.join(__dirname, '..', 'templates', 'scripts', 'sync-eas-version.js'),
      'utf8'
    );
    const projectIdCheck = tpl.indexOf("No projectId — skip EAS sync");
    const gradleRead = tpl.indexOf("readFileSync(GRADLE");
    assert.ok(projectIdCheck !== -1, 'projectId guard should be present');
    assert.ok(gradleRead !== -1, 'gradle read should be present');
    assert.ok(projectIdCheck < gradleRead, 'projectId guard must run before reading build.gradle');
  });
});
