import fs from 'fs';
import path from 'path';
import { Command } from 'commander';
import { confirm } from '@inquirer/prompts';
import kleur from 'kleur';
import { getCtx } from '../util/ctx';
import { log } from '../util/log';

// Keep in sync with src/commands/init.ts.
const TEMPLATE_SCRIPTS = [
  'resolve-project-bin.js',
  'pin-gradle.js',
  'bump-version.js',
  'setup-signing.js',
  'sync-eas-version.js',
  'print-artifact.js',
  'build.js',
];

const VERSION_LINE_RE = /\/\/\s*Generated by local-expo-build v(\d+\.\d+\.\d+)/;

function templatesDir(): string {
  // dist/commands -> ../../templates
  return path.resolve(__dirname, '..', '..', 'templates');
}

function readScriptVersion(filePath: string): string | null {
  try {
    const head = fs.readFileSync(filePath, 'utf8').slice(0, 400);
    const m = head.match(VERSION_LINE_RE);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

interface ScriptStatus {
  name: string;
  userPath: string;
  userVersion: string | null;
  templatePath: string;
  templateVersion: string | null;
  exists: boolean;
  contentDiffers: boolean;
}

function compareScripts(cwd: string): ScriptStatus[] {
  const tplDir = templatesDir();
  const userDir = path.join(cwd, 'scripts');
  return TEMPLATE_SCRIPTS.map((name) => {
    const userPath = path.join(userDir, name);
    const templatePath = path.join(tplDir, 'scripts', name);
    const exists = fs.existsSync(userPath);
    const templateVersion = readScriptVersion(templatePath);
    const userVersion = exists ? readScriptVersion(userPath) : null;
    let contentDiffers = false;
    if (exists) {
      try {
        contentDiffers =
          fs.readFileSync(userPath, 'utf8') !== fs.readFileSync(templatePath, 'utf8');
      } catch {
        contentDiffers = true;
      }
    }
    return { name, userPath, userVersion, templatePath, templateVersion, exists, contentDiffers };
  });
}

export function registerUpdateCommand(program: Command): void {
  program
    .command('update-scripts')
    .description('Refresh scaffolded scripts/*.js to the version bundled with this CLI')
    .option('-y, --yes', 'apply all updates without prompting')
    .action(async (opts, cmd) => {
      const { cwd, dryRun } = getCtx(cmd);
      log.step('local-expo-build update-scripts');
      log.dim(`Target: ${cwd}`);

      const statuses = compareScripts(cwd);
      const needsUpdate = statuses.filter((s) => s.exists && s.contentDiffers);
      const missing = statuses.filter((s) => !s.exists);

      console.log('');
      for (const s of statuses) {
        if (!s.exists) {
          console.log(`  ${kleur.yellow('!')} ${s.name.padEnd(25)} ${kleur.gray('not present (run `init`)')}`);
        } else if (!s.contentDiffers) {
          console.log(
            `  ${kleur.green('✓')} ${s.name.padEnd(25)} ${kleur.gray(`v${s.userVersion || 'unknown'} (up to date)`)}`
          );
        } else {
          console.log(
            `  ${kleur.cyan('↑')} ${s.name.padEnd(25)} ${kleur.gray(
              `v${s.userVersion || 'unknown'} → v${s.templateVersion || '?'} (update available)`
            )}`
          );
        }
      }
      console.log('');

      if (missing.length) {
        log.dim(
          `${missing.length} script(s) missing — run \`npx local-expo-build init\` to scaffold them.`
        );
      }

      if (!needsUpdate.length) {
        log.ok('All scripts are up to date.');
        return;
      }

      if (dryRun) {
        log.warn(`[dry-run] ${needsUpdate.length} script(s) would be overwritten:`);
        for (const s of needsUpdate) log.dim(`  - ${path.relative(cwd, s.userPath).replace(/\\/g, '/')}`);
        return;
      }

      let shouldApply = Boolean(opts.yes);
      if (!shouldApply && process.stdin.isTTY) {
        shouldApply = await confirm({
          message: `Overwrite ${needsUpdate.length} script(s) with the latest bundled version?`,
          default: true,
        });
      } else if (!process.stdin.isTTY && !opts.yes) {
        log.warn('Non-TTY environment and --yes not passed; skipping update.');
        log.dim(`Run: npx local-expo-build update-scripts --yes`);
        return;
      }

      if (!shouldApply) {
        log.dim('Aborted. Run again with --yes to apply.');
        return;
      }

      for (const s of needsUpdate) {
        fs.copyFileSync(s.templatePath, s.userPath);
        log.ok(`Updated ${path.relative(cwd, s.userPath).replace(/\\/g, '/')} → v${s.templateVersion || '?'}`);
      }
      log.ok(`${needsUpdate.length} script(s) refreshed.`);
    });
}
