#!/usr/bin/env node
/**
 * Orchestrates the full local Expo Android build pipeline.
 * Replaces the long `&&` chain in package.json with a single Node entry point.
 * Generated by local-expo-build.
 *
 * Usage: node scripts/build.js (apk|aab) [--dry-run]
 *   --dry-run prints each step without executing it (great for screenshots / sanity checks).
 */
const { execSync } = require('child_process');
const path = require('path');

const args = process.argv.slice(2);
const target = (args.find((a) => !a.startsWith('--')) || 'aab').toLowerCase();
const dryRun = args.includes('--dry-run');

if (target !== 'apk' && target !== 'aab') {
  console.error('Usage: node scripts/build.js (apk|aab) [--dry-run]');
  process.exit(1);
}

const ROOT = path.resolve(__dirname, '..');
const isWin = process.platform === 'win32';
const gradlew = isWin ? 'gradlew.bat' : './gradlew';
const gradleTask = target === 'aab' ? 'bundleRelease' : 'assembleRelease';

const steps = [
  { name: 'expo prebuild',                  cmd: 'npx expo prebuild --platform android', cwd: ROOT },
  { name: 'pin Gradle wrapper',             cmd: 'node scripts/pin-gradle.js',            cwd: ROOT },
  { name: 'bump version',                   cmd: 'node scripts/bump-version.js',          cwd: ROOT },
  { name: 'setup signing (restores .jks)',  cmd: 'node scripts/setup-signing.js',         cwd: ROOT },
  { name: `gradle ${gradleTask}`,           cmd: `${gradlew} ${gradleTask}`,              cwd: path.join(ROOT, 'android') },
  { name: 'sync EAS versionCode',           cmd: 'node scripts/sync-eas-version.js',      cwd: ROOT, allowFail: true },
  { name: 'print artifact',                 cmd: `node scripts/print-artifact.js ${target}`, cwd: ROOT },
];

const dim = (s) => '\x1b[2m' + s + '\x1b[0m';
const bold = (s) => '\x1b[1m' + s + '\x1b[0m';

console.log('\n' + bold(`local-expo-build · ${target.toUpperCase()} · ${steps.length} steps${dryRun ? ' · DRY RUN' : ''}`));
console.log(dim('Local build · saves an EAS cloud build credit · first run is slowest (~5 min)'));
if (dryRun) {
  console.log(dim('No commands will be executed. Each step prints what it would run.\n'));
} else {
  console.log('');
}

const started = Date.now();
for (let i = 0; i < steps.length; i++) {
  const s = steps[i];
  console.log('\n' + bold(`▸ [${i + 1}/${steps.length}] ${s.name}`));
  if (dryRun) {
    const relCwd = path.relative(ROOT, s.cwd) || '.';
    console.log(dim(`  [dry-run] cwd=${relCwd}`));
    console.log(dim(`  [dry-run] ${s.cmd}`));
    if (s.allowFail) console.log(dim('  [dry-run] (non-fatal on failure)'));
    continue;
  }
  try {
    // execSync always uses a shell; omit the option so Node picks the platform default
    // (cmd.exe on Windows, /bin/sh on Unix/macOS).
    execSync(s.cmd, { cwd: s.cwd, stdio: 'inherit' });
  } catch (err) {
    if (s.allowFail) {
      console.warn(dim(`! ${s.name} failed (non-fatal): ${err.message || err}`));
      continue;
    }
    console.error('\n\x1b[31m✗\x1b[0m Build failed at step ' + (i + 1) + ': ' + s.name);
    process.exit(typeof err.status === 'number' ? err.status : 1);
  }
}

if (dryRun) {
  console.log(bold(`\nDRY RUN complete — ${steps.length} steps shown for ${target.toUpperCase()}.`));
  console.log(dim('Re-run without --dry-run to actually build.\n'));
} else {
  const mins = ((Date.now() - started) / 60000).toFixed(1);
  console.log(dim(`\nTotal: ${mins} min\n`));
}
