#!/usr/bin/env node
// Generated by local-expo-build v0.4.3
// To upgrade: npx local-expo-build update-scripts
/**
 * Orchestrates the full local Expo Android build pipeline.
 * Replaces the long `&&` chain in package.json with a single Node entry point.
 *
 * Usage: node scripts/build.js (apk|aab) [--dry-run] [--clean | --no-clean]
 *   --dry-run     prints each step without executing it (great for screenshots / sanity checks).
 *   --clean       force `expo prebuild --clean` (skip the prompt).
 *   --no-clean    force skip --clean (skip the prompt; also the default in CI / non-TTY).
 *
 * When neither --clean nor --no-clean is passed and you're in an interactive
 * terminal, the script asks. Default is NO clean (faster). Pick yes after
 * an Expo SDK upgrade, plugin change, or "android project is malformed" /
 * "MainActivity not found" errors.
 */
const { execSync, spawnSync } = require('child_process');
const readline = require('readline');
const path = require('path');
const { resolveProjectBin, spawnArgs } = require('./resolve-project-bin');

const args = process.argv.slice(2);
const target = (args.find((a) => !a.startsWith('--')) || 'aab').toLowerCase();
const dryRun = args.includes('--dry-run');
const flagClean = args.includes('--clean');
const flagNoClean = args.includes('--no-clean');

if (target !== 'apk' && target !== 'aab') {
  console.error('Usage: node scripts/build.js (apk|aab) [--dry-run] [--clean | --no-clean]');
  process.exit(1);
}

const ROOT = path.resolve(__dirname, '..');
const isWin = process.platform === 'win32';
const gradlew = isWin ? 'gradlew.bat' : './gradlew';
const gradleTask = target === 'aab' ? 'bundleRelease' : 'assembleRelease';

const dim = (s) => '\x1b[2m' + s + '\x1b[0m';
const bold = (s) => '\x1b[1m' + s + '\x1b[0m';

function promptYesNo(message, defaultNo = true) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const hint = defaultNo ? '(y/N)' : '(Y/n)';
    rl.question(`? ${message} ${hint} `, (answer) => {
      rl.close();
      const a = (answer || '').trim().toLowerCase();
      if (!a) return resolve(!defaultNo);
      resolve(a === 'y' || a === 'yes');
    });
  });
}

async function resolveClean() {
  if (flagClean) return true;
  if (flagNoClean) return false;
  if (dryRun || !process.stdin.isTTY) return false;
  return await promptYesNo(
    'Clean android/ before prebuild? (slower, but required after Expo SDK upgrade, ' +
      'plugin change, or "MainActivity not found" / "project is malformed" errors)',
    true
  );
}

(async () => {
  const shouldClean = await resolveClean();
  const expoBin = resolveProjectBin('expo', ROOT);
  if (!expoBin) {
    console.error(
      'expo CLI not found — install dependencies in your project (npm install, bun install, etc.)'
    );
    process.exit(1);
  }
  const prebuildSpawn = spawnArgs(expoBin, [
    'prebuild',
    '--platform',
    'android',
    ...(shouldClean ? ['--clean'] : []),
  ]);

  const steps = [
    { name: 'expo prebuild',                  spawn: prebuildSpawn,                              cwd: ROOT },
    { name: 'pin Gradle wrapper',             cmd: 'node scripts/pin-gradle.js',               cwd: ROOT },
    { name: 'bump version',                   cmd: 'node scripts/bump-version.js',             cwd: ROOT },
    { name: 'setup signing (restores .jks)',  cmd: 'node scripts/setup-signing.js',            cwd: ROOT },
    { name: `gradle ${gradleTask}`,           cmd: `${gradlew} ${gradleTask}`,                 cwd: path.join(ROOT, 'android') },
    { name: 'sync EAS versionCode',           cmd: 'node scripts/sync-eas-version.js',         cwd: ROOT, allowFail: true },
    { name: 'print artifact',                 cmd: `node scripts/print-artifact.js ${target}`, cwd: ROOT },
  ];

  console.log('\n' + bold(`local-expo-build · ${target.toUpperCase()} · ${steps.length} steps${dryRun ? ' · DRY RUN' : ''}${shouldClean ? ' · CLEAN' : ''}`));
  console.log(dim('Local build · saves an EAS cloud build credit · first run is slowest (~5 min)'));
  if (dryRun) {
    console.log(dim('No commands will be executed. Each step prints what it would run.\n'));
  } else {
    console.log('');
  }

  const started = Date.now();
  for (let i = 0; i < steps.length; i++) {
    const s = steps[i];
    console.log('\n' + bold(`▸ [${i + 1}/${steps.length}] ${s.name}`));
    if (dryRun) {
      const relCwd = path.relative(ROOT, s.cwd) || '.';
      console.log(dim(`  [dry-run] cwd=${relCwd}`));
      if (s.spawn) {
        const cmd = [s.spawn.command, ...s.spawn.args].join(' ');
        console.log(dim(`  [dry-run] ${cmd}`));
      } else {
        console.log(dim(`  [dry-run] ${s.cmd}`));
      }
      if (s.allowFail) console.log(dim('  [dry-run] (non-fatal on failure)'));
      continue;
    }
    try {
      if (s.spawn) {
        const result = spawnSync(s.spawn.command, s.spawn.args, {
          cwd: s.cwd,
          stdio: 'inherit',
          shell: s.spawn.shell,
        });
        if (result.status !== 0) {
          const err = new Error(`spawn exited with status ${result.status}`);
          err.status = result.status ?? 1;
          throw err;
        }
      } else {
        // execSync always uses a shell; omit the option so Node picks the platform default
        // (cmd.exe on Windows, /bin/sh on Unix/macOS).
        execSync(s.cmd, { cwd: s.cwd, stdio: 'inherit' });
      }
    } catch (err) {
      if (s.allowFail) {
        console.warn(dim(`! ${s.name} failed (non-fatal): ${err.message || err}`));
        continue;
      }
      console.error('\n\x1b[31m✗\x1b[0m Build failed at step ' + (i + 1) + ': ' + s.name);
      process.exit(typeof err.status === 'number' ? err.status : 1);
    }
  }

  if (dryRun) {
    console.log(bold(`\nDRY RUN complete — ${steps.length} steps shown for ${target.toUpperCase()}.`));
    console.log(dim('Re-run without --dry-run to actually build.\n'));
  } else {
    const mins = ((Date.now() - started) / 60000).toFixed(1);
    console.log(dim(`\nTotal: ${mins} min\n`));
  }
})();
