#!/usr/bin/env node
// Generated by local-expo-build v1.1.1
// To upgrade: npx local-expo-build update-scripts
/**
 * Bumps patch version in app.json + package.json, fetches versionCode from EAS,
 * increments it, and writes both into android/app/build.gradle.
 * Generated by local-expo-build.
 *
 * Usage: node scripts/bump-version.js [profile]   (default profile: production)
 */
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const APP_JSON = path.resolve(__dirname, '../app.json');
const PKG_JSON = path.resolve(__dirname, '../package.json');
const GRADLE = path.resolve(__dirname, '../android/app/build.gradle');
const PROFILE = process.argv[2] || 'production';

const appJson = JSON.parse(fs.readFileSync(APP_JSON, 'utf8'));
const current = appJson.expo.version;
const parts = current.split('.');
if (parts.length !== 3) {
  console.error(`Unexpected version: "${current}" — expected x.y.z with integer segments (e.g. 1.2.3). Pre-release / build-metadata tags (e.g. 1.0.0-rc.1) are not supported.`);
  process.exit(1);
}
const patch = parseInt(parts[2], 10);
if (!Number.isInteger(patch) || String(patch) !== parts[2]) {
  console.error(`Unexpected patch segment "${parts[2]}" in app.json version "${current}" — expected a plain integer (no leading zeros, no pre-release tags).`);
  process.exit(1);
}
parts[2] = String(patch + 1);
const next = parts.join('.');
appJson.expo.version = next;
fs.writeFileSync(APP_JSON, JSON.stringify(appJson, null, 2) + '\n');
console.log(`app.json: ${current} → ${next}`);

const pkg = JSON.parse(fs.readFileSync(PKG_JSON, 'utf8'));
pkg.version = next;
fs.writeFileSync(PKG_JSON, JSON.stringify(pkg, null, 2) + '\n');

let nextCode = null;
if (appJson.expo.extra?.eas?.projectId) {
  try {
    const out = execSync(
      `eas build:version:get --platform android --profile ${PROFILE} --non-interactive`,
      { cwd: path.resolve(__dirname, '..'), encoding: 'utf8', timeout: 30000 }
    );
    // Strip ANSI colors (eas-cli bolds the value when colors are forced) and
    // accept the separator shapes eas-cli has used over time.
    const clean = out.replace(/\x1b\[[0-9;]*m/g, '');
    const m =
      clean.match(/Android\s+versionCode\s*[-–:]\s*(\d+)/i) ||
      clean.match(/versionCode\s*[-–:]\s*(\d+)/i);
    if (m) {
      nextCode = parseInt(m[1], 10) + 1;
      console.log(`EAS versionCode: ${m[1]} → ${nextCode}`);
    } else {
      console.warn('Could not parse EAS versionCode; falling back to local bump');
    }
  } catch (e) {
    // Never built on EAS yet — `build:version:get` fails. Seed the remote
    // version with the local versionCode first, then bump from it.
    const gradleText = fs.existsSync(GRADLE) ? fs.readFileSync(GRADLE, 'utf8') : '';
    const m = gradleText.match(/\bversionCode\s+(\d+)/);
    const localCode = m ? parseInt(m[1], 10) : null;
    if (localCode == null) {
      console.warn('Could not read local versionCode; falling back to local bump');
    } else {
      try {
        execSync(
          `eas build:version:set --platform android --profile ${PROFILE} --version-code ${localCode} --version-name ${current} --non-interactive`,
          { cwd: path.resolve(__dirname, '..'), encoding: 'utf8', timeout: 30000 }
        );
        nextCode = localCode + 1;
        console.log(`Seeded EAS versionCode ${localCode} (first build) → ${nextCode}`);
      } catch (setErr) {
        console.warn('EAS version set failed. (Ensure project is linked and authenticated)');
      }
    }
  }
}

if (!fs.existsSync(GRADLE)) {
  console.error('android/app/build.gradle missing — run prebuild first.');
  process.exit(1);
}
let gradle = fs.readFileSync(GRADLE, 'utf8');
if (nextCode == null) {
  const m = gradle.match(/\bversionCode\s+(\d+)/);
  nextCode = m ? parseInt(m[1], 10) + 1 : 1;
  console.log(`Local versionCode bump → ${nextCode}`);
}
gradle = gradle.replace(/(\bversionCode\s+)\d+/, `$1${nextCode}`);
gradle = gradle.replace(/(\bversionName\s+")[^"]*"/, `$1${next}"`);
fs.writeFileSync(GRADLE, gradle);
console.log(`build.gradle: versionCode=${nextCode}, versionName="${next}"`);
