#!/usr/bin/env node
/**
 * Pins the Android Gradle wrapper to a known-good version after `expo prebuild`.
 * Generated by expo-local-build. Safe to re-run. Edit GRADLE_PIN below if you
 * upgrade Expo SDK.
 */
const fs = require('fs');
const path = require('path');

const GRADLE_PIN = {
  50: null, 51: null, 52: null, 53: null, 54: null,
  55: '8.13',
  56: null,
};

function detectSdkMajor() {
  const pkg = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../package.json'), 'utf8'));
  const raw = (pkg.dependencies && pkg.dependencies.expo) || (pkg.devDependencies && pkg.devDependencies.expo) || '';
  const m = String(raw).match(/(\d+)/);
  return m ? parseInt(m[1], 10) : 0;
}

const sdk = detectSdkMajor();
const PINNED = GRADLE_PIN[sdk];
if (!PINNED) {
  console.log(`[pin-gradle] SDK ${sdk}: no pin required.`);
  process.exit(0);
}

const WRAPPER = path.resolve(__dirname, '..', 'android', 'gradle', 'wrapper', 'gradle-wrapper.properties');
if (!fs.existsSync(WRAPPER)) {
  console.log('[pin-gradle] android/ not yet generated; nothing to do.');
  process.exit(0);
}

const raw = fs.readFileSync(WRAPPER, 'utf8');
const reUrl = /^distributionUrl=.*/m;
const desired = `distributionUrl=https\\://services.gradle.org/distributions/gradle-${PINNED}-bin.zip`;
const current = raw.match(reUrl)?.[0] ?? '';
if (current === desired) {
  console.log(`[pin-gradle] already pinned to Gradle ${PINNED}`);
  process.exit(0);
}
fs.writeFileSync(WRAPPER, raw.replace(reUrl, desired), 'utf8');
console.log(`[pin-gradle] pinned Gradle wrapper to ${PINNED}`);
