#!/usr/bin/env node
// Generated by local-expo-build v0.4.1
// To upgrade: npx local-expo-build update-scripts
/**
 * Pins the Android Gradle wrapper to a known-good version after `expo prebuild`.
 * Fetches the live pin table from GitHub (3s timeout) with a bundled fallback,
 * so a new Expo SDK shipping a problematic Gradle default doesn't require you
 * to re-run `local-expo-build init`.
 * Safe to re-run. Edit GRADLE_PIN below to override per-project.
 */
const fs = require('fs');
const path = require('path');

const GRADLE_PIN = {
  50: null, 51: null, 52: null, 53: null, 54: null,
  55: '8.13',
  56: null,
};

const REMOTE_MANIFEST_URL =
  'https://raw.githubusercontent.com/nikhild64/local-expo-build/main/manifest/gradle-pins.json';

function detectSdkMajor() {
  const pkg = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../package.json'), 'utf8'));
  const raw = (pkg.dependencies && pkg.dependencies.expo) || (pkg.devDependencies && pkg.devDependencies.expo) || '';
  const m = String(raw).match(/(\d+)/);
  return m ? parseInt(m[1], 10) : 0;
}

async function fetchRemotePins() {
  if (typeof fetch !== 'function') return null;
  try {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), 3000);
    const res = await fetch(REMOTE_MANIFEST_URL, { signal: ctl.signal });
    clearTimeout(t);
    if (!res.ok) return null;
    const parsed = await res.json();
    if (!parsed || typeof parsed !== 'object') return null;
    const out = {};
    for (const [k, v] of Object.entries(parsed)) {
      const major = Number(k);
      if (!Number.isInteger(major)) continue;
      if (v === null || typeof v === 'string') out[major] = v;
    }
    return out;
  } catch { return null; }
}

(async () => {
  const sdk = detectSdkMajor();
  const remote = await fetchRemotePins();
  const PINNED = (remote && sdk in remote) ? remote[sdk] : GRADLE_PIN[sdk];
  if (!PINNED) {
    console.log(`[pin-gradle] SDK ${sdk}: no pin required.`);
    process.exit(0);
  }

  const WRAPPER = path.resolve(__dirname, '..', 'android', 'gradle', 'wrapper', 'gradle-wrapper.properties');
  if (!fs.existsSync(WRAPPER)) {
    console.log('[pin-gradle] android/ not yet generated; nothing to do.');
    process.exit(0);
  }

  const raw = fs.readFileSync(WRAPPER, 'utf8');
  const reUrl = /^distributionUrl=.*/m;
  const desired = `distributionUrl=https\\://services.gradle.org/distributions/gradle-${PINNED}-bin.zip`;
  const current = raw.match(reUrl)?.[0] ?? '';
  if (current === desired) {
    console.log(`[pin-gradle] already pinned to Gradle ${PINNED}`);
    process.exit(0);
  }
  fs.writeFileSync(WRAPPER, raw.replace(reUrl, desired), 'utf8');
  console.log(`[pin-gradle] pinned Gradle wrapper to ${PINNED}${remote && sdk in remote ? ' (from remote manifest)' : ''}`);
})();
