#!/usr/bin/env node
// Generated by local-expo-build v1.1.1
// To upgrade: npx local-expo-build update-scripts
/**
 * Injects the release signing config into android/app/build.gradle.
 * Reads credentials from keystore.properties at project root (gitignored).
 * Also restores the .jks into android/app/ if `expo prebuild --clean` wiped it.
 * Uses three injection strategies in order so we survive changes to the
 * Expo prebuild template (whitespace drift, missing debug block, etc.).
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const GRADLE_PATH = path.join(PROJECT_ROOT, 'android', 'app', 'build.gradle');
const PROPS_PATH = path.join(PROJECT_ROOT, 'keystore.properties');

function isNonEmptyFile(p) {
  try { return fs.existsSync(p) && fs.statSync(p).size > 0; } catch { return false; }
}

function ensureKeystoreInAndroidApp(cwd, storeFile) {
  const destDir = path.join(cwd, 'android', 'app');
  const dest = path.join(destDir, storeFile);
  if (isNonEmptyFile(dest)) return;

  const ext = path.extname(storeFile);
  const altExt = ext === '.p12' ? '.jks' : ext === '.jks' ? '.p12' : '';
  const altStoreFile = altExt ? storeFile.slice(0, -ext.length) + altExt : '';

  if (altStoreFile) {
    const altDest = path.join(destDir, altStoreFile);
    if (isNonEmptyFile(altDest)) {
      if (props && props.storeFile) {
        props.storeFile = altStoreFile;
        writePropsFile(PROPS_PATH, props);
        syncCredentialsJson(cwd, props);
      }
      return;
    }
  }

  const candidates = [];

  const credPath = path.join(cwd, 'credentials.json');
  if (fs.existsSync(credPath)) {
    try {
      const cred = JSON.parse(fs.readFileSync(credPath, 'utf8'));
      const ksPath = cred && cred.android && cred.android.keystore && cred.android.keystore.keystorePath;
      if (typeof ksPath === 'string' && ksPath.trim()) {
        const absKs = path.resolve(cwd, ksPath);
        candidates.push(absKs);
        if (altExt) {
          const ksExt = path.extname(absKs);
          const altKsExt = ksExt === '.p12' ? '.jks' : ksExt === '.jks' ? '.p12' : '';
          if (altKsExt) {
            candidates.push(absKs.slice(0, -ksExt.length) + altKsExt);
          }
        }
      }
    } catch (_) {}
  }
  candidates.push(path.join(cwd, 'credentials', 'android', storeFile));
  if (altStoreFile) {
    candidates.push(path.join(cwd, 'credentials', 'android', altStoreFile));
  }
  candidates.push(path.join(cwd, 'credentials', 'android', 'keystore.p12'));
  candidates.push(path.join(cwd, 'credentials', 'android', 'keystore.jks'));
  candidates.push(path.join(cwd, storeFile));
  if (altStoreFile) {
    candidates.push(path.join(cwd, altStoreFile));
  }

  const found = candidates.find((p) => {
    const abs = path.resolve(p);
    return abs !== path.resolve(dest) && isNonEmptyFile(abs);
  });

  if (!found) {
    const tried = candidates.map((p) => '  - ' + path.relative(cwd, p).replace(/\\/g, '/')).join('\n');
    console.error(
      'Keystore file ' + path.relative(cwd, dest).replace(/\\/g, '/') + ' not found, ' +
      'and no recovery source available.\nTried:\n' + tried + '\n\n' +
      'If your android/ directory was just wiped by `expo prebuild --clean`, ' +
      're-run `npx local-expo-build keystore rehydrate` or `keystore import <path>` to restore it.'
    );
    process.exit(1);
  }

  const actualStoreFile = path.basename(found);
  const targetDest = path.join(destDir, actualStoreFile);
  fs.mkdirSync(destDir, { recursive: true });
  fs.copyFileSync(found, targetDest);

  if (actualStoreFile !== storeFile && props) {
    props.storeFile = actualStoreFile;
    writePropsFile(PROPS_PATH, props);
    syncCredentialsJson(cwd, props);
  }

  console.log(
    'Restored keystore: ' + path.relative(cwd, found).replace(/\\/g, '/') +
    ' → ' + path.relative(cwd, targetDest).replace(/\\/g, '/')
  );
}

function writePropsFile(p, pObj) {
  try {
    const lines = [
      `storeFile=${pObj.storeFile}`,
      `storePassword=${pObj.storePassword}`,
      `keyAlias=${pObj.keyAlias}`,
      `keyPassword=${pObj.keyPassword}`,
    ];
    fs.writeFileSync(p, lines.join('\n') + '\n', 'utf8');
  } catch (_) {}
}

// Keeps credentials.json in lock-step with keystore.properties after a
// storeFile swap (alternate-extension restore), so EAS submit / cloud
// builds reference the same .jks that Gradle actually signs with.
function syncCredentialsJson(cwd, pObj) {
  try {
    const credPath = path.join(cwd, 'credentials.json');
    let existing = {};
    if (fs.existsSync(credPath)) {
      existing = JSON.parse(fs.readFileSync(credPath, 'utf8')) || {};
    }
    if (!existing || typeof existing !== 'object' || Array.isArray(existing)) existing = {};
    existing.android = existing.android || {};
    existing.android.keystore = {
      keystorePath: 'android/app/' + pObj.storeFile,
      keystorePassword: pObj.storePassword,
      keyAlias: pObj.keyAlias,
      keyPassword: pObj.keyPassword,
    };
    fs.writeFileSync(credPath, JSON.stringify(existing, null, 2) + '\n', 'utf8');
  } catch (_) {}
}

// The injected release signingConfig embeds plaintext keystore passwords in
// android/app/build.gradle. If that file isn't gitignored, committing the
// android/ directory (CNG) would commit them. git check-ignore is the
// authoritative answer; its exit code 1 means "not ignored" (exit 128 = not a
// git repo, which is also safe to ignore since nothing can be committed).
function warnIfGradleLeaksSecrets() {
  try {
    execSync('git check-ignore --quiet -- android/app/build.gradle', {
      cwd: PROJECT_ROOT,
      stdio: 'ignore',
    });
  } catch (e) {
    if (e && e.status === 1) {
      console.warn(
        '! android/app/build.gradle contains your plaintext keystore passwords and is NOT gitignored.\n' +
        '  If you commit the android/ directory (CNG), your signing passwords will be committed.\n' +
        '  Add android/app/build.gradle to .gitignore, or read the passwords from keystore.properties at build time.'
      );
    }
  }
}

if (!fs.existsSync(PROPS_PATH)) {
  console.error('keystore.properties not found at project root.');
  console.error('Run: npx local-expo-build keystore setup');
  process.exit(1);
}

const props = {};
fs.readFileSync(PROPS_PATH, 'utf8').split('\n').forEach((line) => {
  const t = line.trim();
  if (!t || t.startsWith('#')) return;
  const i = t.indexOf('=');
  if (i === -1) return;
  props[t.slice(0, i).trim()] = t.slice(i + 1).trim();
});

const missing = ['storeFile', 'storePassword', 'keyAlias', 'keyPassword'].filter(
  (k) => !props[k] || props[k] === 'FILL_IN'
);
if (missing.length) {
  console.error(`keystore.properties missing: ${missing.join(', ')}`);
  process.exit(1);
}

if (!fs.existsSync(GRADLE_PATH)) {
  console.error('android/app/build.gradle not found — run `expo prebuild` first.');
  process.exit(1);
}

// Survive `expo prebuild --clean` wiping android/: restore .jks from a stable source.
ensureKeystoreInAndroidApp(PROJECT_ROOT, props.storeFile);

let gradle = fs.readFileSync(GRADLE_PATH, 'utf8');
if (gradle.includes('signingConfigs.release')) {
  console.log('Release signing config already present — skipping.');
  warnIfGradleLeaksSecrets();
  process.exit(0);
}

function findMatchingBrace(s, startSearchFrom) {
  const openIdx = s.indexOf('{', startSearchFrom);
  if (openIdx === -1) return -1;
  let depth = 0;
  for (let i = openIdx; i < s.length; i++) {
    if (s[i] === '{') depth++;
    else if (s[i] === '}') { depth--; if (depth === 0) return i; }
  }
  return -1;
}
function findBlockStart(s, name) {
  const re = new RegExp('\\b' + name + '\\s*\\{');
  const m = re.exec(s);
  return m ? m.index : -1;
}
function releaseBlock(p) {
  return (
    '        release {\n' +
    "            storeFile file('" + p.storeFile + "')\n" +
    "            storePassword '" + p.storePassword + "'\n" +
    "            keyAlias '" + p.keyAlias + "'\n" +
    "            keyPassword '" + p.keyPassword + "'\n" +
    '        }\n'
  );
}

function injectRelease(gradle, p) {
  // Strategy 1: exact match (today's Expo default)
  const EXACT = "    signingConfigs {\n" +
    "        debug {\n" +
    "            storeFile file('debug.keystore')\n" +
    "            storePassword 'android'\n" +
    "            keyAlias 'androiddebugkey'\n" +
    "            keyPassword 'android'\n" +
    "        }\n" +
    "    }";
  const REPLACEMENT = "    signingConfigs {\n" +
    "        debug {\n" +
    "            storeFile file('debug.keystore')\n" +
    "            storePassword 'android'\n" +
    "            keyAlias 'androiddebugkey'\n" +
    "            keyPassword 'android'\n" +
    "        }\n" +
    releaseBlock(p) +
    "    }";
  if (gradle.includes(EXACT)) return { gradle: gradle.replace(EXACT, REPLACEMENT), strategy: 'exact-match' };

  // Strategy 2: tolerant block inject
  const sigStart = findBlockStart(gradle, 'signingConfigs');
  if (sigStart !== -1) {
    const sigEnd = findMatchingBrace(gradle, sigStart);
    if (sigEnd !== -1) {
      return {
        gradle: gradle.slice(0, sigEnd) + releaseBlock(p) + '    ' + gradle.slice(sigEnd),
        strategy: 'block-inject',
      };
    }
  }

  // Strategy 3: synthesize new signingConfigs block inside android { }
  const androidStart = findBlockStart(gradle, 'android');
  if (androidStart !== -1) {
    const openBrace = gradle.indexOf('{', androidStart);
    if (openBrace !== -1) {
      const block = '\n    signingConfigs {\n' + releaseBlock(p) + '    }\n';
      return { gradle: gradle.slice(0, openBrace + 1) + block + gradle.slice(openBrace + 1), strategy: 'synthesize' };
    }
  }
  return null;
}

function wireReleaseBuildType(gradle) {
  const TOKEN = 'signingConfig signingConfigs.debug';
  const RELEASE = 'signingConfig signingConfigs.release';
  const releaseStart = findBlockStart(gradle, 'release');
  if (releaseStart !== -1) {
    const releaseEnd = findMatchingBrace(gradle, releaseStart);
    if (releaseEnd !== -1 && gradle.slice(releaseStart, releaseEnd).includes(RELEASE)) {
      return { gradle: gradle, changed: false };
    }
  }
  const parts = gradle.split(TOKEN);
  if (parts.length >= 3) {
    return {
      gradle: parts[0] + TOKEN + parts[1] + RELEASE + parts.slice(2).join(TOKEN),
      changed: true,
    };
  }
  if (releaseStart !== -1) {
    const releaseEnd = findMatchingBrace(gradle, releaseStart);
    if (releaseEnd !== -1) {
      const slice = gradle.slice(releaseStart, releaseEnd);
      if (slice.includes(TOKEN)) {
        return {
          gradle: gradle.slice(0, releaseStart) + slice.replace(TOKEN, RELEASE) + gradle.slice(releaseEnd),
          changed: true,
        };
      }
    }
  }
  return { gradle: gradle, changed: false };
}

const injected = injectRelease(gradle, props);
if (!injected) {
  console.error(
    'Could not inject the release signingConfig into android/app/build.gradle.\n' +
    'All three strategies failed. Your build.gradle may have been hand-edited or\n' +
    "the Expo prebuild template changed. Add a `release { storeFile file('" + props.storeFile + "') ... }`\n" +
    'block under signingConfigs manually, then re-run.'
  );
  process.exit(1);
}
gradle = injected.gradle;
if (injected.strategy !== 'exact-match') {
  console.log("Used '" + injected.strategy + "' strategy to inject signingConfig.");
}

const wired = wireReleaseBuildType(gradle);
if (!wired.changed) {
  console.warn(
    'Could not locate the release buildType signing line. Check that buildTypes ' +
    'release uses signingConfig signingConfigs.release.'
  );
}
gradle = wired.gradle;

fs.writeFileSync(GRADLE_PATH, gradle, 'utf8');
console.log(`Release signing config injected (alias=${props.keyAlias})`);
warnIfGradleLeaksSecrets();
