#!/usr/bin/env node
/**
 * Injects the release signing config into android/app/build.gradle.
 * Reads credentials from keystore.properties at project root (gitignored).
 * Also restores the .jks into android/app/ if `expo prebuild --clean` wiped it.
 * Generated by expo-local-build.
 */
const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const GRADLE_PATH = path.join(PROJECT_ROOT, 'android', 'app', 'build.gradle');
const PROPS_PATH = path.join(PROJECT_ROOT, 'keystore.properties');

function isNonEmptyFile(p) {
  try { return fs.existsSync(p) && fs.statSync(p).size > 0; } catch { return false; }
}

function ensureKeystoreInAndroidApp(cwd, storeFile) {
  const destDir = path.join(cwd, 'android', 'app');
  const dest = path.join(destDir, storeFile);
  if (isNonEmptyFile(dest)) return;

  const candidates = [];

  const credPath = path.join(cwd, 'credentials.json');
  if (fs.existsSync(credPath)) {
    try {
      const cred = JSON.parse(fs.readFileSync(credPath, 'utf8'));
      const ksPath = cred && cred.android && cred.android.keystore && cred.android.keystore.keystorePath;
      if (typeof ksPath === 'string' && ksPath.trim()) {
        candidates.push(path.resolve(cwd, ksPath));
      }
    } catch (_) {}
  }
  candidates.push(path.join(cwd, 'credentials', 'android', storeFile));
  candidates.push(path.join(cwd, 'credentials', 'android', 'keystore.jks'));
  candidates.push(path.join(cwd, storeFile));

  const found = candidates.find((p) => {
    const abs = path.resolve(p);
    return abs !== path.resolve(dest) && isNonEmptyFile(abs);
  });

  if (!found) {
    const tried = candidates.map((p) => '  - ' + path.relative(cwd, p).replace(/\\/g, '/')).join('\n');
    console.error(
      'Keystore file ' + path.relative(cwd, dest).replace(/\\/g, '/') + ' not found, ' +
      'and no recovery source available.\nTried:\n' + tried + '\n\n' +
      'If your android/ directory was just wiped by `expo prebuild --clean`, ' +
      're-run `npx expo-local-build keystore rehydrate` or `keystore import <path>` to restore it.'
    );
    process.exit(1);
  }

  fs.mkdirSync(destDir, { recursive: true });
  fs.copyFileSync(found, dest);
  console.log(
    'Restored keystore: ' + path.relative(cwd, found).replace(/\\/g, '/') +
    ' → ' + path.relative(cwd, dest).replace(/\\/g, '/')
  );
}

if (!fs.existsSync(PROPS_PATH)) {
  console.error('keystore.properties not found at project root.');
  console.error('Run: npx expo-local-build keystore setup');
  process.exit(1);
}

const props = {};
fs.readFileSync(PROPS_PATH, 'utf8').split('\n').forEach((line) => {
  const t = line.trim();
  if (!t || t.startsWith('#')) return;
  const i = t.indexOf('=');
  if (i === -1) return;
  props[t.slice(0, i).trim()] = t.slice(i + 1).trim();
});

const missing = ['storeFile', 'storePassword', 'keyAlias', 'keyPassword'].filter(
  (k) => !props[k] || props[k] === 'FILL_IN'
);
if (missing.length) {
  console.error(`keystore.properties missing: ${missing.join(', ')}`);
  process.exit(1);
}

if (!fs.existsSync(GRADLE_PATH)) {
  console.error('android/app/build.gradle not found — run `expo prebuild` first.');
  process.exit(1);
}

// Survive `expo prebuild --clean` wiping android/: restore .jks from a stable source.
ensureKeystoreInAndroidApp(PROJECT_ROOT, props.storeFile);

let gradle = fs.readFileSync(GRADLE_PATH, 'utf8');
if (gradle.includes('signingConfigs.release')) {
  console.log('Release signing config already present — skipping.');
  process.exit(0);
}

const DEFAULT = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`;

const REPLACEMENT = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file('${props.storeFile}')
            storePassword '${props.storePassword}'
            keyAlias '${props.keyAlias}'
            keyPassword '${props.keyPassword}'
        }
    }`;

if (!gradle.includes(DEFAULT)) {
  console.error('Could not find default signingConfigs block in build.gradle.');
  process.exit(1);
}
gradle = gradle.replace(DEFAULT, REPLACEMENT);

const TOKEN = 'signingConfig signingConfigs.debug';
const parts = gradle.split(TOKEN);
if (parts.length >= 3) {
  gradle = parts[0] + TOKEN + parts[1] + 'signingConfig signingConfigs.release' + parts.slice(2).join(TOKEN);
}
fs.writeFileSync(GRADLE_PATH, gradle, 'utf8');
console.log(`Release signing config injected (alias=${props.keyAlias})`);
