import fs from 'fs';
import path from 'path';

/** Keep in sync across init, update-scripts, and update checks. */
export const TEMPLATE_SCRIPTS = [
  'resolve-project-bin.js',
  'pin-gradle.js',
  'bump-version.js',
  'setup-signing.js',
  'sync-eas-version.js',
  'print-artifact.js',
  'build.js',
] as const;

const VERSION_LINE_RE = /\/\/\s*Generated by local-expo-build v(\d+\.\d+\.\d+)/;

export function templatesDir(): string {
  // dist/core -> ../../templates
  return path.resolve(__dirname, '..', '..', 'templates');
}

export function readScriptVersion(filePath: string): string | null {
  try {
    const head = fs.readFileSync(filePath, 'utf8').slice(0, 400);
    const m = head.match(VERSION_LINE_RE);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

export interface ScriptStatus {
  name: string;
  userPath: string;
  userVersion: string | null;
  templatePath: string;
  templateVersion: string | null;
  exists: boolean;
  contentDiffers: boolean;
}

export function compareScripts(cwd: string): ScriptStatus[] {
  const tplDir = templatesDir();
  const userDir = path.join(cwd, 'scripts');
  return TEMPLATE_SCRIPTS.map((name) => {
    const userPath = path.join(userDir, name);
    const templatePath = path.join(tplDir, 'scripts', name);
    const exists = fs.existsSync(userPath);
    const templateVersion = readScriptVersion(templatePath);
    const userVersion = exists ? readScriptVersion(userPath) : null;
    let contentDiffers = false;
    if (exists) {
      try {
        contentDiffers =
          fs.readFileSync(userPath, 'utf8') !== fs.readFileSync(templatePath, 'utf8');
      } catch {
        contentDiffers = true;
      }
    }
    return { name, userPath, userVersion, templatePath, templateVersion, exists, contentDiffers };
  });
}

export function hasScaffoldedScripts(cwd: string): boolean {
  return compareScripts(cwd).some((s) => s.exists);
}

export function getOutdatedScripts(cwd: string): ScriptStatus[] {
  return compareScripts(cwd).filter((s) => s.exists && s.contentDiffers);
}

export function applyScriptUpdates(scripts: ScriptStatus[]): void {
  for (const s of scripts) {
    fs.copyFileSync(s.templatePath, s.userPath);
  }
}
